adicionando readme pamplonacarlos
LeandraOS/GuiaMarkdown pull request #32
Opened 2022-10-13 17:36 UTC by PamplonaCarlos

2022-10-13 17:50 UTC, LeandraOS requested changes

2022-10-13 17:50 UTC, LeandraOS commented on Contribuições/README-Profile/pamplonacarlos.md
> +<h1 align="left">Seja bem-vind@!</h1>
Oiee @PamplonaCarlos, recomendo que tu troque as tags HTML utilizadas pelas suas correspondentes em Markdown. [Esse guia](https://github.com/LeandraOS/GuiaMarkdown/blob/main/GuiaMarkdown.md) pode te ajudar nessa tradução. Em alguns casos entendo que não dá para trocar o HTML pelo Markdown, mas no que possível peço que mudes pra ficar bem no estilo dos demais README'S que temos aqui 🚀

2022-10-13 17:52 UTC, PamplonaCarlos commented on Contribuições/README-Profile/pamplonacarlos.md
> +<h1 align="left">Seja bem-vind@!</h1>
tudo certo!!

2022-10-13 18:47 UTC, PamplonaCarlos commented on Contribuições/README-Profile/pamplonacarlos.md
> +<h1 align="left">Seja bem-vind@!</h1>
feito!

2022-10-14 02:51 UTC, LeandraOS approved these changes
Ficou ótimo :rocket:

2022-10-14 02:51 UTC, merged